# Site settings
title: "The Armory"
author: "Saph, Traneptora"
description:
  "A searchable D&D 5e item list, sorted by rarity."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://armory.thebombzen.xyz" # the base hostname & protocol for your site
source-url: "https://github.com/Traneptora/armory/"
permalink: "/:categories/:title"
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

# Build settings
markdown: kramdown
highlighter: pygments

# Site defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: "spells"
